pan_tilt_camera:
  ros__parameters:
    video_device: 0
    frame_rate: 10
    # video_device: "/dev/video1"
    # time_per_frame: [1, 30] # Set the desired FPS here
    # image_size: [640, 480]
    # output_encoding: "yuv422_yuy2"

fisheye_camera:
  ros__parameters:
    video_device: 2
    frame_rate: 10
    # video_device: "/dev/video1"
    # time_per_frame: [1, 30] # Set the desired FPS here
    # image_size: [640, 480]
    # output_encoding: "yuv422_yuy2"
